services:
  # docker container run --rm -it --name consul-dev -p 8500:8500 hashicorp/consul:1.12.0
  # agent -dev -dns-port 53 -client 0.0.0.0 -recursor 1.1.1.1
  consul-dev:
    image: hashicorp/consul:1.12.0
    ports:
      - "8500:8500"
    networks:
      default:
        ipv4_address: 172.18.0.2
    volumes:
      - ./conf:/consul/config
  # docker container run --rm -it -p 5000:5000 --name shipments weshigbee/consul2-shipments
  shipments:
    image: weshigbee/consul2-shipments
    ports:
      - "5000:5000"
    networks:
      default:
        ipv4_address: 172.18.0.3
  # docker container run --rm -it -p 3000:3000 --name orders -e "SHIPMENTS_URL=http://shipments.service.consul:5000" --dns 172.17.0.4 weshigbee/consul2-orders
  orders:
    image: weshigbee/consul2-orders
    ports:
      - "3000:3000"
    dns:
      - 172.18.0.2
    environment:
      SHIPMENTS_URL: http://shipments.service.consul:5000
      SMTP_HOST: smtp.service.consul
    networks:
      default:
        ipv4_address: 172.18.0.4
  #
  mails:
    image: mailhog/mailhog
    ports:
    - "8025:8025"
    # port 1025 = SMTP
    networks:
      default:
        ipv4_address: 172.18.0.6
  #
  # run one-off DNS queries:
  #   docker compose run dog shipments.service.consul
  dog:
    image: weshigbee/consul2-dog
    dns:
      - 172.18.0.2
    profiles:
      - runonly

networks:
  default:
    ipam:
      config:
        - subnet: "172.18.0.0/24"
          ip_range: "172.18.0.0/24"
          gateway: "172.18.0.1"
