services:
  consul-dev:
    image: hashicorp/consul:1.12.0
    ports:
      - "8500:8500"
    networks:
      default:
        ipv4_address: 10.0.1.20
    volumes:
      - ./conf:/consul/config

networks:
  default:
    ipam:
      config:
        - subnet: "10.0.0.0/16"
          gateway: "10.0.0.1"
