services:

  server1:
    image: hashicorp/consul:1.12.0
    hostname: server1
    volumes:
      - ./conf/server.hcl:/consul/config/server.hcl
    command: [ "agent" ]
    ports:
      - "8500:8500"
    networks:
      default:
        ipv4_address: 10.0.1.20

  # think 'machine cs' or 'pod cs' (shared netns)
  cs:
    image: hashicorp/consul:1.12.0
    hostname: cs
    volumes:
      - ./conf/client.hcl:/consul/config/client.hcl
      - ./conf/cs/shipments.hcl:/consul/config/shipments.hcl
    command: [ "agent" ]
    ports:
      - "19001:19001"
    dns:
      - 127.0.0.1
  ship:
    image: weshigbee/consul2-shipments
    network_mode: "service:cs"
    entrypoint:
      [
        "envconsul",
        "-consul-addr=10.0.1.20:8500",
        "-prefix=shipments/",
        "-log-level=debug",
        "-upcase",
        "dotnet /app/shipments.dll"
      ]
  ship-sc:
    image: weshigbee/consul2-envoy
    network_mode: "service:cs"
    command:
      [
        "consul",
        "connect",
        "envoy",
        "-sidecar-for=shipments1",
        "-admin-bind=0.0.0.0:19001"
      ]

  # pod co (shared netns)
  co:
    image: hashicorp/consul:1.12.0
    hostname: co
    volumes:
      - ./conf/client.hcl:/consul/config/client.hcl
      - ./conf/co/orders.hcl:/consul/config/orders.hcl
    command: [ "agent" ]
    ports:
      - "3000:3000"
      - "19000:19000"
    dns:
      - 127.0.0.1
  orders:
    image: weshigbee/consul2-orders
    network_mode: "service:co"
    environment:
      LOG_LEVEL: verbose
      SHIPMENTS_URL: http://localhost:6000 # http://shipments.service.consul:5000
      SMTP_HOST: smtp.service.consul
  orders-sc:
    image: weshigbee/consul2-envoy
    network_mode: "service:co"
    command:
      [
        "consul",
        "connect",
        "envoy",
        "-sidecar-for=orders1",
        "-admin-bind=0.0.0.0:19000"
      ]
  
  # 'pod cmt' (shared netns)
  cmt:
    image: hashicorp/consul:1.12.0
    hostname: cmt
    volumes:
      - ./conf/client.hcl:/consul/config/client.hcl
      - ./conf/cmt/smtp.hcl:/consul/config/smtp.hcl
      - ./conf/cmt/tracking.hcl:/consul/config/tracking.hcl
    command: [ "agent" ]
    ports:
      - "8025:8025"
      - "19002:19002"
  mail:
    image: mailhog/mailhog
    network_mode: "service:cmt"
  tracking:
    image: weshigbee/consul2-tracking
    network_mode: "service:cmt"
  track-sc:
    image: weshigbee/consul2-envoy
    network_mode: "service:cmt"
    command:
      [
        "consul",
        "connect",
        "envoy",
        "-sidecar-for=tracking1",
        "-admin-bind=0.0.0.0:19002"
      ]

networks:
  default:
    ipam:
      config:
        - subnet: "10.0.0.0/16"
          gateway: "10.0.0.1"
