# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/jammy64' # ubuntu 22.04

  config.vm.hostname = 'install'

  # explicit IP to access VM (and thus consul services)
  config.vm.network 'private_network', ip: '192.168.56.10'

  config.vm.provision :shell, privileged: false, path: 'provision/install.helpers.sh'
  # config.vm.provision :shell, privileged: false, path: 'provision/install.consul.sh'

  config.vm.provider 'virtualbox' do |vb|
    # vb.gui = true
    vb.memory = '4096'
    vb.cpus = 4
  end
end
